"""empty message

Revision ID: 7ef4ef059c4d
Revises: 5c6dbf2f2c0d
Create Date: 2022-05-21 10:03:05.520145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from alembic.ddl import postgresql

from aiogram_modul.crypto_graphy import EncodeDecodeService

revision = '7ef4ef059c4d'
down_revision = '5c6dbf2f2c0d'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Budgeting', 'amount', type_=sa.String(500), existing_type=sa.FLOAT)

    connection = op.get_bind()
    results = connection.execute('SELECT id, amount FROM "Budgeting"').fetchall()
    for pk, amount in results:
        encode_amount = EncodeDecodeService().encode_amount(str(amount))
        query_sql = f"""UPDATE "Budgeting" SET amount = '{encode_amount}' WHERE id = {pk}"""
        connection.execute(query_sql)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    results = connection.execute('SELECT id, amount FROM "Budgeting"').fetchall()
    for pk, amount in results:
        encode_amount = EncodeDecodeService().decode_amount(str(amount))
        query_sql = f"""UPDATE "Budgeting" SET amount = '{encode_amount}' WHERE id = {pk}"""
        connection.execute(query_sql)

    op.execute('ALTER TABLE "Budgeting" ALTER COLUMN amount TYPE double precision USING amount::double precision')
    ### end Alembic commands ###
