"""hash_category_name

Revision ID: 820b1376cc83
Revises: 7ef4ef059c4d
Create Date: 2022-05-28 01:23:10.023711

"""
from alembic import op


# revision identifiers, used by Alembic.
from aiogram_modul.crypto_graphy import EncodeDecodeService

revision = '820b1376cc83'
down_revision = '7ef4ef059c4d'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    results = connection.execute('SELECT id, name FROM "Category"').fetchall()
    for pk, name in results:
        encode_name = EncodeDecodeService().encode(name)
        query_sql = f"""UPDATE "Category" SET name = '{encode_name}' WHERE id = {pk}"""
        connection.execute(query_sql)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    results = connection.execute('SELECT id, name FROM "Category"').fetchall()
    for pk, name in results:
        decode_name = EncodeDecodeService().decode(name)
        query_sql = f"""UPDATE "Category" SET name = '{decode_name}' WHERE id = {pk}"""
        connection.execute(query_sql)
    ### end Alembic commands ###
